import os

FACEBOOK_CLIENT_ID = os.environ.get("FOTRINO_FACEBOOK_CLIENT_ID") or None
FACEBOOK_CLIENT_SECRET = os.environ.get("FOTRINO_FACEBOOK_CLIENT_SECRET") or None

GOOGLE_CLIENT_ID = os.environ.get("FOTRINO_GOOGLE_CLIENT_ID") or None
GOOGLE_CLIENT_SECRET = os.environ.get("FOTRINO_GOOGLE_CLIENT_SECRET") or None

GITHUB_CLIENT_ID = os.environ.get("FOTRINO_GITHUB_CLIENT_ID") or None
GITHUB_CLIENT_SECRET = os.environ.get("FOTRINO_GITHUB_CLIENT_SECRET") or None

REDDIT_CLIENT_ID = os.environ.get("FOTRINO_REDDIT_CLIENT_ID") or None
REDDIT_CLIENT_SECRET = os.environ.get("FOTRINO_REDDIT_CLIENT_SECRET") or None

INSTAGRAM_CLIENT_ID = os.environ.get("FOTRINO_INSTAGRAM_CLIENT_ID") or None
INSTAGRAM_CLIENT_SECRET = os.environ.get("FOTRINO_INSTAGRAM_CLIENT_SECRET") or None

GITLAB_CLIENT_ID = os.environ.get("FOTRINO_GITLAB_CLIENT_ID") or None
GITLAB_CLIENT_SECRET = os.environ.get("FOTRINO_GITLAB_CLIENT_SECRET") or None

LINKEDIN_CLIENT_ID = os.environ.get("FOTRINO_LINKEDIN_CLIENT_ID") or None
LINKEDIN_CLIENT_SECRET = os.environ.get("FOTRINO_LINKEDIN_CLIENT_SECRET") or None

STACKOVERFLOW_CLIENT_ID = os.environ.get("FOTRINO_STACKOVERFLOW_CLIENT_ID") or None
STACKOVERFLOW_CLIENT_SECRET = os.environ.get("FOTRINO_STACKOVERFLOW_CLIENT_SECRET") or None

HYDRA_CLIENT_ID = os.environ.get("FOTRINO_HYDRA_CLIENT_ID") or None
HYDRA_CLIENT_SECRET = os.environ.get("FOTRINO_HYDRA_CLIENT_SECRET") or None
